name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 0.7.4
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons
authors:
  - Flutter Community <community@flutter.zone>
  - Franz Silva <franzsilva@gmail.com>
  - Mark O'Sullivan <mos182@hotmail.co.uk>
  - Simon Lightfoot <simon@devangels.london>

dependencies:
  image: 2.1.7
  args: 1.5.2
  yaml: 2.2.0
  path: 1.6.4

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: 1.9.3
  crypto: 2.1.3
